# Generated by Django 2.1.2 on 2019-09-28 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='is_avaliable',
            new_name='is_available',
        ),
    ]
