# Generated by Django 2.1.2 on 2019-09-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_manager', '0002_auto_20190928_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
