# Generated by Django 2.1.2 on 2019-09-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_manager', '0003_auto_20190928_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.TextField(null=True),
        ),
    ]
